Repository FoE-Info/FoE-Info-Extension, pull requests merged in 2022-12, with the labels that each got.

#40 fix issue #35
  src/js/msg/ConversationService.js
  src/js/msg/GreatBuildingsService.js
Labels: bug, enhancement

#41 fix: to handle Hr in thread name
  src/js/msg/ConversationService.js
Labels: bug

#43 additional fixes for Issue #35
  src/js/msg/ConversationService.js
Labels: bug

#42 Fix: copy button on Treasury Contributions, Issue #33
  src/js/fn/collapse.js
  src/js/fn/copy.js
  src/js/index.js
Labels: bug

#44 City Info panel collapses when hitting the copy button and copies the word Copy #37
  src/js/fn/collapse.js
  src/js/msg/StartupService.js
Labels: bug

#48 gvg-total-power-all
  src/js/msg/ClanBattleService.js
Labels: enhancement
